### ISSUE TITLE
Template: Add multiple line capability to Report: Title

### ISSUE THREAD

**Issue by mvandenbos** [mvandenbos/steuerbescheinigungen-spender#4]
In the template, under Report, please add the ability to have a title with multiple lines.

example: 
Anlage zur Sammelzuwendungsbestätigung vom 10.01.2019 
Aussteller: Christliche Gemeinde Heidelsheim e.V.

**Comment by koehdaniel** [comment]
Added a new field called report.subtitle for the second row.
Or do you prefer another approach?
