### ISSUE TITLE
Template-Import not working

### ISSUE THREAD

**Issue by koehdaniel** [mvandenbos/steuerbescheinigungen-spender#43]
After importing a TEMPLATE_EXPORT the `LetterHead.subheader`s are overwritten by the `Letter.subheader`s and other fields as well. It seems as if the Parent-Element is not considered at all.

**Comment by mvandenbos** [comment]
You were right, during the recursion, if a sub-item had the same name as another sub-item it did not check if it was the right parent element or not before updating it.  I have been able to resolve this and a commit is coming soon.
